server:
  port: 9090
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth_service
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
security:
  oauth2:
    client:
      clientId: rsoi-client
      clientSecret: rsoi-client-secret
      authorized-grant-types:
        - authorization_code
        - refresh_token
        - password
      scope: openid
    resource:
      jwt:
        key-store: keystore.jks
        key-store-password: mystorepass
        key-alias: mytestkey
